apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: contour-rolebinding
roleRef:
  kind: Role
  name: contour-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: contour
- kind: ServiceAccount
  name: contour-certgen
